#!/bin/sh

# Wait for the property system to be up.
while [ ! -e /dev/socket/property_service ]; do sleep 0.1; done

# Wait for nvram to be loaded.
while [ "$(getprop vendor.service.nvram_init)" != "Ready" ]; do sleep 0.2; done
while [ "$(getprop vendor.mtk.nvram.ready)" != "1" ]; do sleep 0.2; done

# enable Wi-Fi adapter in client mode
while [ ! -e /sys/class/wmtWifi/wmtWifi/dev ]; do sleep 0.2; done

if [ ! -e /dev/wmtWifi ]; then
    dev=$(cat /sys/class/wmtWifi/wmtWifi/dev)
    major=${dev%%:*}
    mknod /dev/wmtWifi c $major 0
fi
echo S > /dev/wmtWifi

# set wifi.interface property since urfkill.conf expects that
setprop wifi.interface wlan0

# create device nodes for rfkill and vhci
if [ ! -e /dev/rfkill ]; then
    mknod /dev/rfkill c 10 242
fi
if [ ! -e /dev/vhci ]; then
    mknod /dev/vhci c 10 137
fi
